---
label: product
hide_body: true
fields:
- type: text
  name: id
  label: id
- type: text
  name: name
  label: name
- type: number
  name: price
  label: price
- type: textarea
  name: description
  label: description
- type: file
  name: image
  label: image
- type: text
  name: product_url
  label: product_url
- type: datetime
  name: date
  label: date
- type: text
  name: url
  label: url
pages:
- content/products/kitten.md
